DROP TABLE PLACES;

CREATE TABLE places(
	place_id SERIAL PRIMARY KEY,
	country VARCHAR(100) NOT NULL,
	city VARCHAR(100) NOT NULL,
	place_name VARCHAR(100) NOT NULL,
	address VARCHAR(100) NOT NULL,
	sport_name VARCHAR(100) REFERENCES sports(sport_name),
	cost DOUBLE PRECISION 
);

INSERT INTO places (country, city, place_name, address, sport_name, cost) 
VALUES
	('Bangladesh', 'Winston Salem', 'North Carolina', 'Warrior', 'ski', 100),
	('Bangladesh', 'Fresno', 'California', 'Park Meadow', 'ski', 10),
	('Bangladesh', 'Apache Junction', 'Arizona', 'Gerald', 'ski', 56),
	('Bangladesh', 'Oklahoma City', 'Oklahoma', 'Manitowish', 'ski', 70),
	('Bulgaria', 'Las Vegas', 'Nevada', 'Artisan', 'ski', 345),
	('Burundi', 'Zephyrhills', 'Florida', 'Fuller', 'ski', 200),
	('Burundi', 'Albuquerque', 'New Mexico', 'Mariners Cove', 'bungee_jumping', 15.66),
	('Burundi', 'Charlotte', 'North Carolina', 'Calypso', 'bungee_jumping', 16.18),
	('Cyprus', 'Denver', 'Colorado', 'Sycamore', 'bungee_jumping', 1934),
	('Cyprus', 'Pueblo', 'Colorado', 'Bayside', 'bungee_jumping', 56),
	('Djibouti', 'Aurora', 'Illinois', 'Springview', 'bungee_jumping', 10),
	('Djibouti', 'Denver', 'Colorado', 'Del Sol', 'zorbing', 15),
	('Djibouti', 'Springfield', 'Illinois', 'Bunting', 'zorbing', 19),
	('Egypt', 'Norfolk', 'Virginia', 'Northfield', 'zorbing', 20),
	('Egypt', 'Albany', 'Georgia', '1st', 'zorbing', 22),
	('Egypt', 'Birmingham', 'Alabama', 'Claremont', 'zorbing', 25),
	('Finland', 'San Francisco', 'California', 'Fuller', 'ice_climbing', 27),
	('Finland', 'Aurora', 'Colorado', 'Pepper Wood', 'ice_climbing', 30),
	('Finland', 'Washington', 'District of Columbia', 'Basil', 'ice_climbing', 450),
	('Honduras', 'Anchorage', 'Alaska', 'Briar Crest', 'ice_climbing', 11),
	('Honduras', 'Torrance', 'California', 'Hanover', 'slacklining', 12),
	('Honduras', 'Lincoln', 'Nebraska', 'Starling', 'slacklining', 13),
	('Indonesia', 'Bloomington', 'Indiana', 'Ilene', 'slacklining', 14),
	('Indonesia', 'Asheville', 'North Carolina', 'Melody', 'slacklining', 20),
	('Indonesia', 'Jacksonville', 'Florida', '1st', 'slacklining', 30),
	('Indonesia', 'Amarillo', 'Texas', 'Huxley', 'slacklining', 40),
	('Ireland', 'Dayton', 'Ohio', 'Hauk', 'kitesurfing', 10),
	('Ireland', 'Washington', 'District of Columbia', 'Forster', 'kitesurfing', 12),
	('Ireland', 'Colorado Springs', 'Colorado', 'Sunfield', 'kitesurfing', 16),
	('Lebanon', 'Santa Ana', 'California', 'Vahlen', 'kitesurfing', 19),
	('Lebanon', 'Louisville', 'Kentucky', 'Acker', 'kitesurfing', 22),
	('Lebanon', 'Aurora', 'Colorado', 'Express', 'kitesurfing', 1500),
	('Lebanon', 'Anaheim', 'California', 'Gateway', 'skydiving', 2),
	('Moldova', 'Fort Wayne', 'Indiana', 'North', 'skydiving', 3),
	('Moldova', 'Charlotte', 'North Carolina', 'Ruskin', 'skydiving', 90),
	('Moldova', 'Brooklyn', 'New York', 'Sundown', 'skydiving', 69),
	('Moldova', 'Houston', 'Texas', 'Bonner', 'skydiving', 62),
	('Norway', 'Fayetteville', 'North Carolina', 'Thompson', 'zip-lining', 64),
	('Norway', 'Ann Arbor', 'Michigan', 'Helena', 'zip-lining', 48),
	('Norway', 'Los Angeles', 'California', 'Marquette', 'zip-lining', 10),
	('Norway', 'Roanoke', 'Virginia', 'Northfield', 'zip-lining', 88),
	('Slovakia', 'Dallas', 'Texas', 'Bultman', 'zip-lining', 80),
	('Slovakia', 'Dallas', 'Texas', 'Vermont', 'zip-lining', 140),
	('Slovakia', 'Punta Gorda', 'Florida', 'Manufacturers', 'snowmobiling', 215),
	('Slovakia', 'New Orleans', 'Louisiana', 'Lakewood', 'snowmobiling', 16),
	('United States', 'Monroe', 'Louisiana', 'Red Cloud', 'snowmobiling', 17),
	('United States', 'Los Angeles', 'California', 'Welch', 'snowmobiling', 90),
	('United States', 'Moreno Valley', 'California', 'Lerdahl', 'snowmobiling', 45),
	('United States', 'Hartford', 'Connecticut', 'Banding', 'coasteering', 66),
	('United States', 'Santa Barbara', 'California', 'Arkansas', 'coasteering', 709);